version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseball-stats-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=baseball_stats_back

  db:
    image: postgres:15
    container_name: baseball-stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: baseball_stats_back
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
